services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: bakey-website-local
    restart: unless-stopped
