name: ci

on:
  push:
    branches: [
      master,
    ]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get shortsha
        id: vars
        run: |
         echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Prep Tag
        id: prep
        env:
          SHORTSHA: ${{ steps.vars.outputs.sha_short }}
        run: |
          echo ::set-output name=tags::ghcr.io/bak3y/bakey.us:$SHORTSHA
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
  do-deploy:
    runs-on: self-hosted
    needs: docker-build-and-push
    steps:
      - name: Pull and run image
        uses: addnab/docker-run-action@v1
        env:
          SHORTSHA: ${{ steps.vars.outputs.sha_short }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
          image: bakey.us:$SHORTSHA
        