name: ci-cd

on:
  push:
    branches: [main]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/bak3y/bakey.us:latest
  do-deploy:
    runs-on: self-hosted
    environment: digitalocean
    needs: docker-build-and-push
    steps:
      - name: docker Login
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: pull image
        run: |
          docker pull ghcr.io/bak3y/bakey.us:latest
      - name: stop old container
        run: |
          docker stop bakey.us || exit 0
      - name: docker system prune
        run: |
          docker system prune -af
      - name: run new container
        run: |
          docker run --name bakey.us -v /etc/letsencrypt/:/etc/letsencrypt/ -p 80:80 -p 443:443 -d ghcr.io/bak3y/bakey.us:latest
